from playwright.sync_api import sync_playwright


def test_page():
    with sync_playwright() as p:
        browser = p.chromium.launch(headless = False)
        page = browser.new_page()
        context = browser.new_context()
        context.tracing.start(screenshots=True, snapshots=True, sources=True)
        page.goto("http://tutorialsninja.com/demo/")
        page.get_by_role("link", name="Laptops & Notebooks").first.click()
        page.get_by_role("link", name="Show All Laptops & Notebooks").click()
        page.locator("#content").get_by_role("link", name="Macs (0)").click()
        page.get_by_role("link", name="Components (2)").click()
        page.get_by_role("link", name="Laptops & Notebooks (5)").click()
        page.get_by_role("link", name="MacBook Air").first.click()
        page.get_by_label("Qty").click()
        page.get_by_label("Qty").fill("3")
        page.get_by_role("button", name="Add to Cart").click()
        page.get_by_role("button", name=" 3 item(s) - $3,606.00").click()
        page.get_by_role("link", name=" View Cart").click()
        page.get_by_role("heading", name="Use Coupon Code ").click()
        page.get_by_role("link", name="Use Coupon Code ").click()
        page.get_by_placeholder("Enter your coupon here").click()
        page.get_by_placeholder("Enter your coupon here").fill("123456abcdefg")
        page.get_by_role("link", name="Continue Shopping").click()
        page.get_by_role("link", name=" My Account").click()
        page.get_by_role("link", name="Register").click()
        page.get_by_placeholder("First Name").click()
        page.get_by_placeholder("First Name").fill("manoj")
        page.get_by_placeholder("Last Name").click()
        page.get_by_placeholder("Last Name").fill("kumar")
        page.get_by_placeholder("E-Mail").click()
        page.get_by_placeholder("E-Mail").fill("xyz@gmail")
        page.get_by_placeholder("E-Mail").click()
        page.get_by_placeholder("E-Mail").fill("xyz@gmail.com")
        page.get_by_placeholder("Telephone").click()
        page.get_by_placeholder("Telephone").fill("1234567890")
        page.locator("#input-password").click()
        page.locator("#input-password").fill("xyz@123")
        page.get_by_placeholder("Password Confirm").click()
        page.get_by_placeholder("Password Confirm").fill("xyz@123")
        page.get_by_text("Yes").click()
        page.get_by_role("checkbox").check()
        page.get_by_role("button", name="Continue").click()
        page.get_by_role("button", name="Continue").click()
        page.get_by_placeholder("E-Mail").click()
        page.get_by_placeholder("E-Mail").fill("xyz@gmail.com")
        page.get_by_placeholder("E-Mail").press("ArrowLeft")
        page.get_by_placeholder("E-Mail").press("ArrowLeft")
        page.get_by_placeholder("E-Mail").press("ArrowLeft")
        page.get_by_placeholder("E-Mail").press("ArrowLeft")
        page.get_by_placeholder("E-Mail").press("ArrowLeft")
        page.get_by_placeholder("E-Mail").press("ArrowLeft")
        page.get_by_placeholder("E-Mail").press("ArrowLeft")
        page.get_by_placeholder("E-Mail").fill("xyz12345@gmail.com")
        page.get_by_role("button", name="Continue").click()
        page.get_by_role("button", name=" 3 item(s) - $3,606.00").click()
        page.get_by_role("link", name=" View Cart").click()
        page.get_by_role("link", name="Your Store").click()
        context.tracing.stop(path="trace.zip")

    test_page(p)