def test_run(page, credentials):
    # username = credentials["username"]
    # password = credentials["password"]
    page.goto("https://www.adidas.co.in/")
    page.get_by_role("link", name="log in").click()
    page.get_by_role("textbox", name="Email").fill("test.mail199302@gmail.com")
    page.get_by_role("textbox", name="Password").fill("Test_mail93")
    page.get_by_role("checkbox", name="Keep me logged in. More info").click()
    page.get_by_role("button", name="Log in").click()
    # page.locator("//a[@role='menu'][normalize-space()='MEN']").click()
    # page.locator("//section[@data-testid='teaser-block-wrapper']//section[1]//a[1]").click()
    # page.get_by_role("img", name="Men Basketball Blue Trae HC Hoodie").click()
    # page.get_by_role("button", name="2XL").click()
    # page.get_by_role("button", name="ADD TO BAG").click()
    # page.get_by_role("link", name="VIEW BAG").click()
    # page.get_by_role("button", name="Checkout").click()
    page.get_by_role("link", name="log in").click()
    page.get_by_role("tab", name="ACCOUNT").click()
    page.locator("//a[normalize-space()='Address Book']").click()
    page.locator("//div[@data-auto-id='add-new-address']//div[1]").click()
    page.get_by_role("textbox", name="First Name").fill("Test")
    page.get_by_role("textbox", name="Last Name").fill("Mail")
    page.get_by_role("textbox", name="Street Address").fill("ASV chandilya towers")
    page.get_by_role("textbox", name="Landmark").fill("OMR")
    page.get_by_role("textbox", name="Additional info").fill("8th Floor")
    page.get_by_role("textbox", name="City").fill("Chennai")
    page.get_by_role("textbox", name="Pin Code").fill("600098")
    page.get_by_role("button", name="State").click()
    page.locator("//button[@value='Tamil Nadu']").click()
    page.locator("//input[@aria-label='Mobile Number']").fill("8247472876")
    page.get_by_role("button", name="SAVE").click()
    page.locator("//a[normalize-space()='Log out']").click()
